# Generated by Django 3.2.7 on 2021-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('performance_review', models.ManyToManyField(to='performance_review.PerformanceReview')),
            ],
        ),
    ]
