# Generated by Django 3.2.7 on 2021-10-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOnOneReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_note', models.CharField(max_length=360)),
                ('manager_note', models.CharField(max_length=360)),
                ('subordinate_note', models.CharField(max_length=360)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_on_one_reviews_manager', to='profile.profile')),
                ('subordinate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_on_one_reviews_subordinate', to='profile.profile')),
            ],
        ),
    ]
