# Generated by Django 3.1.7 on 2021-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_part', models.CharField(max_length=512)),
                ('plans', models.CharField(max_length=512)),
            ],
        ),
    ]
