# Generated by Django 3.1.7 on 2021-11-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perforator', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
