# Generated by Django 3.2.9 on 2021-11-13 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('perforator', '0009_auto_20211105_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('sbis', models.CharField(max_length=128)),
                ('photo', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('peers', models.ManyToManyField(blank=True, default=None, null=True, related_name='_perforator_profile_peers_+', to='perforator.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='self_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='PUser',
        ),
    ]
