# Generated by Django 3.2.9 on 2021-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perforator', '0011_averagegrade_grade_gradecategory_performancereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='manager_review_categories',
            field=models.ManyToManyField(default=None, related_name='manager_review_categories', to='perforator.GradeCategory'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='peers_review_categories',
            field=models.ManyToManyField(default=None, related_name='peers_review_categories', to='perforator.GradeCategory'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='self_review_categories',
            field=models.ManyToManyField(default=None, related_name='self_review_categories', to='perforator.GradeCategory'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='team_review_categories',
            field=models.ManyToManyField(default=None, related_name='team_review_categories', to='perforator.GradeCategory'),
        ),
    ]
