# Generated by Django 3.2.9 on 2021-12-08 20:26

from django.db import migrations, models
import django.db.models.deletion
import perforator.models


class Migration(migrations.Migration):

    dependencies = [
        ('perforator', '0012_auto_20211119_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='perforator.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='peers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='i_am_peer_to', to='perforator.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=perforator.models.savePhotoUnderRandomName),
        ),
    ]
