# Generated by Django 3.1.7 on 2021-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perforator', '0015_profile_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecategory',
            name='preview_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
