# Generated by Django 3.2.7 on 2021-10-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('grade_category', '0001_initial'),
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_grade', models.FloatField()),
                ('normalized_grade', models.FloatField()),
                ('evaluated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
                ('grade_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grade_category.gradecategory')),
                ('performance_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_review.performancereview')),
            ],
        ),
    ]
