# Generated by Django 3.2.7 on 2021-10-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraising_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraising_person', to='profile.profile')),
                ('evaluated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_person', to='profile.profile')),
            ],
        ),
    ]
