# Generated by Django 3.2.7 on 2021-10-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '__first__'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='performance_review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='performance_review', to='performance_review.performancereview'),
        ),
    ]
