# Generated by Django 3.2.7 on 2021-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_performance_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
