# Generated by Django 3.1.7 on 2021-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perforator', '0007_remove_puser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
