# Generated by Django 3.2.9 on 2021-12-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perforator', '0013_auto_20211201_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='perforator.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='peers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='i_am_peer_to', to='perforator.Profile'),
        ),
        migrations.CreateModel(
            name='PeerReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlines', models.CharField(max_length=512)),
                ('approaches', models.CharField(max_length=512)),
                ('teamwork', models.CharField(max_length=512)),
                ('practices', models.CharField(max_length=512)),
                ('experience', models.CharField(max_length=512)),
                ('adaptation', models.CharField(max_length=512)),
                ('rates_deadlines', models.CharField(max_length=512)),
                ('rates_approaches', models.IntegerField(choices=[(1, 'Lower'), (2, 'Low'), (3, 'High'), (4, 'Higher')])),
                ('rates_teamwork', models.IntegerField(choices=[(1, 'Lower'), (2, 'Low'), (3, 'High'), (4, 'Higher')])),
                ('rates_practices', models.IntegerField(choices=[(1, 'Lower'), (2, 'Low'), (3, 'High'), (4, 'Higher')])),
                ('rates_experience', models.IntegerField(choices=[(1, 'Lower'), (2, 'Low'), (3, 'High'), (4, 'Higher')])),
                ('rates_adaptation', models.IntegerField(choices=[(1, 'Lower'), (2, 'Low'), (3, 'High'), (4, 'Higher')])),
                ('peer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_reviews', to='perforator.profile')),
                ('rated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reviews', to='perforator.profile')),
            ],
        ),
    ]
