# Generated by Django 3.2.9 on 2021-12-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perforator', '0014_auto_20211206_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
