# Generated by Django 3.2.7 on 2021-10-10 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profile.profile')),
                ('peers', models.ManyToManyField(related_name='_profile_profile_peers_+', to='profile.Profile')),
                ('team', models.ManyToManyField(related_name='_profile_profile_team_+', to='profile.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
